apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: "${APP_NAME}-config-template"
labels:
  template: "${APP_NAME}-config-template"
parameters:
  - name: APP_NAME
    description: Application name used to identify the ConfigMap
    required: true
  - name: ROOT_LOG_LEVEL
    description: Default log threshold (TRACE, DEBUG, INFO, WARN, ERROR, OFF)
    value: "INFO"
  - name: APP_LOG_LEVEL
    description: Address Change application log threshold
    value: "INFO"
  - name: SPRING_WEB_LOG_LEVEL
    description: Spring Web log threshold
    value: "INFO"
  - name: SPRING_BOOT_AUTOCONFIG_LOG_LEVEL
    description: Spring Boot auto-configuration logging threshold
    value: "INFO"
  - name: SERVICE_ENVIRONMENT
    description: Deployment environment (DEV, TEST, PROD) for ECS service.environment
    required: true
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "${APP_NAME}-config"
      labels:
        app: "${APP_NAME}"
    data:
      SERVICE_ENVIRONMENT: "${SERVICE_ENVIRONMENT}"
      ROOT_LOG_LEVEL: "${ROOT_LOG_LEVEL}"
      APP_LOG_LEVEL: "${APP_LOG_LEVEL}"
      SPRING_WEB_LOG_LEVEL: "${SPRING_WEB_LOG_LEVEL}"
      SPRING_BOOT_AUTOCONFIG_LOG_LEVEL: "${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}"
