apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: "${APP_NAME}-config-template"
labels:
  template: "${APP_NAME}-config-template"
parameters:
  - name: APP_NAME
    description: Application name used to identify the ConfigMap
    required: true
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "${APP_NAME}-config"
      labels:
        app: "${APP_NAME}"
    data: {}
