# Automated tasks that run during a PR
name: Pull request checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**/src/**"
      - "**/pom.xml"
permissions:
  contents: read

env:
  JAVA_VERSION: "25"

jobs:
  quality_profile:
    name: Compile, test, and analyze
    runs-on: ubuntu-24.04

    steps:
      - name: Check out source
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
          cache-dependency-path: api/pom.xml

      - name: Compile and run unit tests
        run: bash ./mvnw --batch-mode -f api/pom.xml clean verify

      - name: Cache Sonar packages
        uses: actions/cache@v6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Run Sonar analysis
        run: >
          bash ./mvnw --batch-mode -f api/pom.xml
          org.sonarsource.scanner.maven:sonar-maven-plugin:5.7.0.6970:sonar
          -Dsonar.host.url="${{ vars.SONAR_HOST_URL }}"
          -Dsonar.organization="${{ vars.SONAR_ORG }}"
          -Dsonar.projectKey="${{ vars.SONAR_PROJECT_KEY }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
